### ISSUE TITLE
> You should not use dartz package, made your owns Result class

### ISSUE THREAD

**Issue by MatiasFino** [MatiasFino/Movie#5]
> You should not use dartz package, made your owns Result class

is it okey if I use this library: `either.dart`?
because I made my own state managment solution based on that:
typedef EitherMovieAPI<T> = Either<Failure, T>;

_Originally posted by @MatiasFino in https://github.com/MatiasFino/Movie/issues/4#issuecomment-1781196196_

**Comment by FranciscoGaraventa** [comment]
Remove also Either implementation, you don't need to depend of that kind of libraries, as a suggestion made your own implementations
